name: Build Sphinx Docs

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 2

    steps:
    - name: Clone the code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
        cache: 'pip'
        cache-dependency-path: |
          pyproject.toml
          requirements/*.txt

    - name: Make a virtualenv
      run: python3 -m venv .venv

    - name: Install requirements
      run: |
        source .venv/bin/activate
        pip install uv==0.1.40
        uv pip install --requirement requirements/docs.txt

    - name: Run Linter
      run: |
        source .venv/bin/activate
        sphinx-lint --sort-by filename docs/

    - name: Build documentation
      run: |
        source .venv/bin/activate
        make docs
